##############################################
#         Archivo de Configuración           #
#          Nimter Framework 1.0.9            #
##############################################

#Configuración de la base de datos
database:
  driver: mysql
  host: localhost
  name: 
  user: root
  pwd: 
  port: 3306
  codification: utf8
  timezone: es_MX

#Configuración del cifrado
security:
  secret_key: 123456
  secret_iv: 123456
  method: AES-256-CBC

#Configuracón de las rutas
path:
  views: App/Views/
  controllers: App/Controllers/
  models: App/Models/

#Configuración general operativa del Framework
general:
  timezone: America/Mexico_City
  language: spanish
  path: http://localhost/Horizon/
  debug: true

#Configuración de Twig
twig:
  compiler: Core/compiler/
  reload: true

#Datos del desarrollador
developer:
  author: Alexis Mora
  company:  Nimter
  email:  alexis.mora@correo.com